const songList = [
  ["Shiny Smily Story (2022 ver.)", "", { easy: 1, normal: 8, hard: 16, expert: 22 }, "Shiny Smily Story (2022 ver.).jpg"],
  ["青春アーカイブ", "", { easy: 2, normal: 10, hard: 17, expert: 24 }, "青春アーカイブ.jpg"],
  ["夢見る空へ", "", { easy: 3, normal: 9, hard: 17, expert: 25 }, "夢見る空へ.jpg"],
  ["キラメキライダー☆", "", { easy: 5, normal: 12, hard: 17, expert: 24 }, "キラメキライダー☆.jpg"],
  ["Dreaming Days", "", { easy: 3, normal: 10, hard: 17, expert: 23 }, "Dreaming Days.jpg"],
  ["あすいろClearSky", "", { easy: 4, normal: 11, hard: 19, expert: 24 }, "あすいろClearSky.jpg"],
  ["Prism Melody", "", { easy: 4, normal: 11, hard: 18, expert: 25 }, "Prism Melody.jpg"],
  ["Our Bright Parade", "", { easy: 3, normal: 10, hard: 17, expert: 27 }, "Our Bright Parade.jpg"],
  ["Capture the Moment", "", { easy: 4, normal: 9, hard: 17, expert: 23 }, "Capture the Moment.jpg"],
  ["Color Rise Harmony", "", { easy: 6, normal: 13, hard: 20, expert: 27 }, "Color Rise Harmony.jpg"],
  ["Ridin\u0027 on Dreams", "", { easy: 6, normal: 12, hard: 18, expert: 25 }, "Ridin\u0027 on Dreams.jpg"],
  ["夢色ワンダー", "", { easy: 4, normal: 14, hard: 23, expert: 29 }, "夢色ワンダー.jpg"],
  ["BLUE CLAPPER", "", { easy: 6, normal: 14, hard: 19, expert: 26 }, "BLUE CLAPPER.jpg"],
  ["ギミギミエンターテイメント", "", { easy: 5, normal: 11, hard: 20, expert: 27 }, "ギミギミエンターテイメント.jpg"],
  ["Dream☆Story", "", { easy: 4, normal: 10, hard: 19, expert: 25 }, "Dream☆Story.jpg"],
  ["スタースタースタート", "", { easy: 4, normal: 14, hard: 20, expert: 25 }, "スタースタースタート.jpg"],
  ["リルビ", "", { easy: 6, normal: 12, hard: 18, expert: 26 }, "リルビ.jpg"],
  ["ω猫", "", { easy: 9, normal: 16, hard: 23, expert: 28 }, "ω猫.jpg"],
  ["いのち(2024 ver.)", "", { easy: 1, normal: 9, hard: 15, expert: 22 }, "いのち(2024 ver.).jpg"],
  ["flower rhapsody", "", { easy: 3, normal: 9, hard: 18, expert: 25 }, "flower rhapsody.jpg"],
  ["DAI DAI DAI ファンタジスタ", "", { easy: 5, normal: 11, hard: 19, expert: 25 }, "DAI DAI DAI ファンタジスタ.jpg"],
  ["Stellar Stellar", "", { easy: 3, normal: 10, hard: 17, expert: 25 }, "Stellar Stellar.jpg"],
  ["ビビデバ", "", { easy: 2, normal: 9, hard: 16, expert: 25 }, "ビビデバ.jpg"],
  ["シャルイース", "", { easy: 1, normal: 12, hard: 16, expert: 23 }, "シャルイース.jpg"],
  ["感触", "", { easy: 3, normal: 10, hard: 18, expert: 27 }, "感触.jpg"],
  ["SUPERNOVA", "", { easy: 7, normal: 14, hard: 20, expert: 26 }, "SUPERNOVA.jpg"],
  ["ばーちゃらぶ", "", { easy: 8, normal: 14, hard: 22, expert: 28 }, "ばーちゃらぶ.jpg"],
  ["宵の余、良い！", "", { easy: 6, normal: 12, hard: 20, expert: 25 }, "宵の余、良い！.jpg"],
  ["NoDistance", "", { easy: 6, normal: 13, hard: 20, expert: 26 }, "NoDistance.jpg"],
  ["ぷ・れ・あ・で・す！", "", { easy: 4, normal: 12, hard: 18, expert: 26 }, "ぷ・れ・あ・で・す！.jpg"],
  ["Howling", "", { easy: 4, normal: 9, hard: 18, expert: 25 }, "Howling.jpg"],
  ["Colorful Universe", "", { easy: 5, normal: 12, hard: 19, expert: 27 }, "Colorful Universe.jpg"],
  ["もぐもぐYUMMY！", "", { easy: 6, normal: 12, hard: 19, expert: 25 }, "もぐもぐYUMMY！.jpg"],
  ["ネコカブリーナ", "", { easy: 6, normal: 12, hard: 20, expert: 26 }, "ネコカブリーナ.jpg"],
  ["Doggy god\u0027s street", "", { easy: 7, normal: 13, hard: 20, expert: 26 }, "Doggy god\u0027s street.jpg"],
  ["ぺこらんだむぶれいん!", "", { easy: 6, normal: 13, hard: 20, expert: 27 }, "ぺこらんだむぶれいん!.jpg"],
  ["全人類　兎化計画！", "", { easy: 6, normal: 12, hard: 20, expert: 26 }, "全人類　兎化計画！.jpg"],
  ["全力ジャンピング！", "", { easy: 4, normal: 11, hard: 18, expert: 24 }, "全力ジャンピング！.jpg"],
  ["ぎゅーどんかーにばる！", "", { easy: 5, normal: 13, hard: 19, expert: 27 }, "ぎゅーどんかーにばる！.jpg"],
  ["Ahoy!! 我ら宝鐘海賊団☆", "", { easy: 5, normal: 12, hard: 18, expert: 25 }, "Ahoy!! 我ら宝鐘海賊団☆.jpg"],
  ["美少女無罪♡パイレーツ", "", { easy: 4, normal: 11, hard: 19, expert: 25 }, "美少女無罪♡パイレーツ.jpg"],
  ["My song", "", { easy: 4, normal: 13, hard: 20, expert: 27 }, "My song.jpg"],
  ["What an amazing swing", "", { easy: 6, normal: 12, hard: 20, expert: 27 }, "What an amazing swing.jpg"],
  ["Palette", "", { easy: 3, normal: 11, hard: 16, expert: 24 }, "Palette.jpg"],
  ["守護ってルーナイト", "", { easy: 5, normal: 11, hard: 19, expert: 26 }, "守護ってルーナイト.jpg"],
  ["明日への境界線", "", { easy: 4, normal: 11, hard: 19, expert: 25 }, "明日への境界線.jpg"],
  ["ねねねねねねねね！大爆走", "", { easy: 7, normal: 12, hard: 20, expert: 27 }, "ねねねねねねねね！大爆走.jpg"],
  ["Lioness’ Pride", "", { easy: 5, normal: 11, hard: 18, expert: 26 }, "Lioness’ Pride.jpg"],
  ["ぽ", "", { easy: 8, normal: 15, hard: 22, expert: 28 }, "ぽ.jpg"],
  ["興味ないよ", "", { easy: 3, normal: 10, hard: 17, expert: 25 }, "興味ないよ.jpg"],
  ["オーバード", "", { easy: 4, normal: 13, hard: 19, expert: 27 }, "オーバード.jpg"],
  ["WAO!!(2025 ver.)", "", { easy: 6, normal: 13, hard: 20, expert: 25 }, "WAO!!(2025 ver.).jpg"],
  ["いろはすてっぷ！", "", { easy: 4, normal: 11, hard: 17, expert: 25 }, "いろはすてっぷ！.jpg"],
  ["ALiCE\u0026u", "", { easy: 3, normal: 12, hard: 17, expert: 24 }, "ALiCE\u0026u.jpg"],
  ["High Tide", "", { easy: 4, normal: 12, hard: 18, expert: 26 }, "High Tide.jpg"],
  ["Q\u0026A=E", "", { easy: 4, normal: 10, hard: 17, expert: 24 }, "Q\u0026A=E.jpg"],
  ["JOLLIE JOLLIE", "", { easy: 6, normal: 13, hard: 19, expert: 25 }, "JOLLIE JOLLIE.jpg"],
  ["アンリアルヴェイル", "", { easy: 6, normal: 15, hard: 21, expert: 26 }, "アンリアルヴェイル.jpg"],
  ["Gate Open: START!", "", { easy: 4, normal: 12, hard: 18, expert: 26 }, "Gate Open_ START!.jpg"],
  ["You\u0027re Mine", "", { easy: 3, normal: 9, hard: 16, expert: 24 }, "You\u0027re Mine.jpg"],
  ["dahlah.", "", { easy: 3, normal: 12, hard: 16, expert: 24 }, "dahlah.jpg"],
  ["Mantra Hujan", "", { easy: 4, normal: 11, hard: 18, expert: 25 }, "Mantra Hujan.jpg"],
  ["失礼しますが、RIP♡", "", { easy: 5, normal: 12, hard: 18, expert: 27 }, "失礼しますが、RIP♡.jpg"],
  ["DEAD BEATS", "", { easy: 3, normal: 11, hard: 18, expert: 27 }, "DEAD BEATS.jpg"],
  ["SPARKS", "", { easy: 5, normal: 12, hard: 19, expert: 25 }, "SPARKS.jpg"],
  ["VIOLET", "", { easy: 2, normal: 9, hard: 16, expert: 24 }, "VIOLET.jpg"],
  ["Carbonated Love", "", { easy: 6, normal: 14, hard: 21, expert: 28 }, "Carbonated Love.jpg"],
  ["Daydream", "", { easy: 1, normal: 9, hard: 15, expert: 23 }, "Daydream.jpg"],
  ["PSYCHO", "", { easy: 7, normal: 14, hard: 21, expert: 29 }, "PSYCHO.jpg"],
  ["Monsters and Men", "", { easy: 7, normal: 14, hard: 20, expert: 29 }, "Monsters and Men.jpg"],
  ["プリズムの魔法", "", { easy: 2, normal: 10, hard: 16, expert: 23 }, "プリズムの魔法.jpg"],
  ["Say My Name", "", { easy: 5, normal: 9, hard: 16, expert: 24 }, "Say My Name.jpg"],
  ["Lifetime Showtime", "", { easy: 8, normal: 13, hard: 21, expert: 28 }, "Lifetime Showtime.jpg"],
  ["Born to be \"BAU\"DOL☆★", "", { easy: 5, normal: 12, hard: 20, expert: 27 }, "Born to be _BAU_DOL☆★.jpg"],
  ["GREATEST", "", { easy: 3, normal: 11, hard: 19, expert: 26 }, "GREATEST.jpg"],
  ["今日も大天才っ！", "", { easy: 6, normal: 14, hard: 22, expert: 27 }, "今日も大天才っ！.jpg"],
  ["JAPANの美術史♪お·ぼ·え·ま·SHOW！", "", { easy: 5, normal: 11, hard: 19, expert: 26 }, "JAPANの美術史♪お·ぼ·え·ま·SHOW！.jpg"],
  ["Countach", "", { easy: 4, normal: 10, hard: 18, expert: 26 }, "Countach.jpg"],
  ["Myth or Treat", "", { easy: 4, normal: 12, hard: 19, expert: 26 }, "Myth or Treat.jpg"],
  ["Secret Garden", "", { easy: 5, normal: 10, hard: 17, expert: 27 }, "Secret Garden.jpg"],
  ["常夜リペイント", "", { easy: 6, normal: 11, hard: 19, expert: 27 }, "常夜リペイント.jpg"],
  ["ブライダルドリーム", "", { easy: 5, normal: 13, hard: 21, expert: 27 }, "ブライダルドリーム.jpg"],
  ["Our Promise", "", { easy: 3, normal: 9, hard: 15, expert: 24 }, "Our Promise.jpg"],
  ["Rebellion", "", { easy: 4, normal: 11, hard: 19, expert: 25 }, "Rebellion.jpg"],
  ["HI-15", "", { easy: 4, normal: 13, hard: 18, expert: 26 }, "HI-15.jpg"],
  ["Slap by Step", "", { easy: 6, normal: 15, hard: 21, expert: 28 }, "Slap by Step.jpg"],
  ["save our hearts", "", { easy: 2, normal: 10, hard: 17, expert: 26 }, "save our hearts.jpg"],
  ["瞬間ハートビート", "", { easy: 4, normal: 11, hard: 16, expert: 24 }, "瞬間ハートビート.jpg"],
  ["刹那ティックコード", "", { easy: 3, normal: 12, hard: 21, expert: 26 }, "刹那ティックコード.jpg"],
  ["Suspect", "", { easy: 3, normal: 10, hard: 18, expert: 25 }, "Suspect.jpg"],
  ["なかま歌", "", { easy: 8, normal: 15, hard: 21, expert: 28 }, "なかま歌.jpg"],
  ["Wicked feat. Mori Calliope", "", { easy: 2, normal: 9, hard: 19, expert: 26 }, "Wicked feat. Mori Calliope.jpg"],
  ["おにけもだんす", "", { easy: 8, normal: 14, hard: 23, expert: 27 }, "おにけもだんす.jpg"],
  ["地獄で会おうぜ！ スバちょこるなたん", "", { easy: 6, normal: 13, hard: 22, expert: 28 }, "地獄で会おうぜ！ スバちょこるなたん.jpg"],
  ["ORANGE PARADE feat.戌神ころね", "", { easy: 6, normal: 12, hard: 20, expert: 27 }, "ORANGE PARADE feat.戌神ころね.jpg"],
  ["I I I", "", { easy: 5, normal: 12, hard: 18, expert: 26 }, "I I I.jpg"],
  ["ししわたクッキング feat.獅白ぼたん", "", { easy: 5, normal: 10, hard: 19, expert: 25 }, "ししわたクッキング feat.獅白ぼたん.jpg"],
  ["また傷に触れる", "", { easy: 5, normal: 11, hard: 17, expert: 26 }, "また傷に触れる.jpg"],
  ["青く在れ", "", { easy: 8, normal: 14, hard: 22, expert: 28 }, "青く在れ.jpg"],
  ["みっころね×しょうたいむ!!", "", { easy: 3, normal: 10, hard: 18, expert: 26 }, "みっころね×しょうたいむ!!.jpg"],
  ["鬼ノ宴", "", { easy: 4, normal: 11, hard: 19, expert: 25 }, "鬼ノ宴.jpg"],
  ["気まぐれメルシィ", "", { easy: 5, normal: 12, hard: 19, expert: 27 }, "気まぐれメルシィ.jpg"],
  ["ブタサンダー", "", { easy: 5, normal: 10, hard: 17, expert: 23 }, "ブタサンダー.jpg"],
  ["シル・ヴ・プレジデント", "", { easy: 5, normal: 11, hard: 21, expert: 25 }, "シル・ヴ・プレジデント.jpg"],
  ["同担☆拒否", "", { easy: 3, normal: 9, hard: 17, expert: 25 }, "同担☆拒否.jpg"],
  ["グッバイ宣言", "", { easy: 4, normal: 12, hard: 20, expert: 26 }, "グッバイ宣言.jpg"],
  ["妄想税", "", { easy: 3, normal: 12, hard: 18, expert: 25 }, "妄想税.jpg"],
  ["どぅーまいべすと！", "", { easy: 3, normal: 11, hard: 18, expert: 26 }, "どぅーまいべすと！.jpg"],
  ["唱", "", { easy: 1, normal: 11, hard: 18, expert: 24 }, "唱.jpg"],
  ["怪物", "", { easy: 4, normal: 12, hard: 19, expert: 26 }, "怪物.jpg"],
  ["寝起きヤシの木", "", { easy: 1, normal: 11, hard: 19, expert: 25 }, "寝起きヤシの木.jpg"],
  ["-ERROR", "", { easy: 4, normal: 9, hard: 16, expert: 25 }, "-ERROR.jpg"],
  ["ふわふわ時間", "", { easy: 2, normal: 9, hard: 17, expert: 24 }, "ふわふわ時間.jpg"],
  ["勇者", "", { easy: 5, normal: 12, hard: 20, expert: 26 }, "勇者.jpg"],
  ["ちゅ、多様性。", "", { easy: 5, normal: 14, hard: 20, expert: 25 }, "ちゅ、多様性。.jpg"],
  ["ノンブレス・オブリージュ", "", { easy: 4, normal: 11, hard: 19, expert: 27 }, "ノンブレス・オブリージュ.jpg"],
  ["エンヴィーベイビー", "", { easy: 7, normal: 12, hard: 19, expert: 26 }, "エンヴィーベイビー.jpg"],
  ["神っぽいな", "", { easy: 5, normal: 13, hard: 19, expert: 26 }, "神っぽいな.jpg"],
  ["フクロウさん", "", { easy: 3, normal: 11, hard: 18, expert: 26 }, "フクロウさん.jpg"],
  ["God knows...", "", { easy: 4, normal: 11, hard: 19, expert: 26 }, "God knows.jpg"],
  ["きゅうくらりん", "", { easy: 2, normal: 14, hard: 21, expert: 27 }, "きゅうくらりん.jpg"],
  ["Snow halation", "", { easy: 2, normal: 11, hard: 17, expert: 24 }, "Snow halation.jpg"],
  ["FIRE BIRD", "", { easy: 5, normal: 13, hard: 20, expert: 29 }, "FIRE BIRD.jpg"],
  ["エイリアンエイリアン", "", { easy: 7, normal: 14, hard: 21, expert: 26 }, "エイリアンエイリアン.jpg"],
  ["狂乱 Hey Kids!!", "", { easy: 6, normal: 14, hard: 19, expert: 26 }, "狂乱 Hey Kids!!.jpg"],
  ["マーシャル・マキシマイザー", "", { easy: 7, normal: 14, hard: 21, expert: 28 }, "マーシャル・マキシマイザー.jpg"],
  ["うっせぇわ", "", { easy: 4, normal: 13, hard: 19, expert: 25 }, "うっせぇわ.jpg"],
  ["可愛くてごめん", "", { easy: 3, normal: 11, hard: 16, expert: 23 }, "可愛くてごめん.jpg"],
  ["brave heart", "", { easy: 2, normal: 9, hard: 16, expert: 22 }, "brave heart.jpg"],
  ["Overdose", "", { easy: 4, normal: 12, hard: 17, expert: 24 }, "Overdose.jpg"],
  ["ヴァンパイア", "", { easy: 5, normal: 13, hard: 21, expert: 26 }, "ヴァンパイア.jpg"],
  ["ないない", "", { easy: 5, normal: 9, hard: 18, expert: 25 }, "ないない.jpg"],
  ["アイドル", "", { easy: 2, normal: 11, hard: 20, expert: 26 }, "アイドル.jpg"],
  ["マフィア", "", { easy: 3, normal: 10, hard: 16, expert: 25 }, "マフィア.jpg"],
  ["Los! Los! Los!", "", { easy: 7, normal: 12, hard: 20, expert: 27 }, "Los! Los! Los!.jpg"],
  ["強風オールバック", "", { easy: 3, normal: 10, hard: 17, expert: 24 }, "強風オールバック.jpg"],
  ["鏡面の波", "", { easy: 1, normal: 9, hard: 16, expert: 24 }, "鏡面の波.jpg"],
  ["雪の華", "", { easy: 1, normal: 8, hard: 15, expert: 22 }, "雪の華.jpg"],
  ["キュートなカノジョ", "", { easy: 4, normal: 11, hard: 18, expert: 26 }, "キュートなカノジョ.jpg"],
  ["Let Me Be With You", "", { easy: 5, normal: 10, hard: 17, expert: 24 }, "Let Me Be With You.jpg"],
  ["奏（かなで）", "", { easy: 1, normal: 8, hard: 15, expert: 23 }, "奏（かなで）.jpg"],
  ["チェリーポップ", "", { easy: 7, normal: 14, hard: 23, expert: 28 }, "チェリーポップ.jpg"],
  ["ピ ピカソ", "", { easy: 4, normal: 13, hard: 19, expert: 25 }, "ピ ピカソ.jpg"],
  ["ツッパリHigh School Rock\u0027n Roll(登校編)", "", { easy: 4, normal: 10, hard: 16, expert: 24 }, "ツッパリHigh School Rock\u0027n Roll(登校編).jpg"],
  ["回レ！雪月花", "", { easy: 5, normal: 14, hard: 19, expert: 27 }, "回レ！雪月花.jpg"],
  ["デビルじゃないもん", "", { easy: 6, normal: 13, hard: 18, expert: 27 }, "デビルじゃないもん.jpg"],
  ["ハオ", "", { easy: 5, normal: 13, hard: 21, expert: 26 }, "ハオ.jpg"],
  ["わたしの一番かわいいところ", "", { easy: 4, normal: 9, hard: 17, expert: 26 }, "わたしの一番かわいいところ.jpg"],
  ["メギツネ", "", { easy: 8, normal: 13, hard: 21, expert: 28 }, "メギツネ.jpg"],
  ["ヒャダインのじょーじょーゆーじょー", "", { easy: 8, normal: 16, hard: 23, expert: 29 }, "ヒャダインのじょーじょーゆーじょー.jpg"],
  ["再会", "", { easy: 1, normal: 9, hard: 16, expert: 22 }, "再会.jpg"],
  ["神のまにまに", "", { easy: 4, normal: 10, hard: 20, expert: 25 }, "神のまにまに.jpg"],
  ["い～やい～やい～や", "", { easy: 3, normal: 11, hard: 17, expert: 26 }, "い～やい～やい～や.jpg"],
  ["選んでくれてありがとう。", "", { easy: 2, normal: 10, hard: 16, expert: 23 }, "選んでくれてありがとう。.jpg"],
];

const songDetailPageMap = {};
